module("pt_game", package.seeall)

MDM_MB_LOGON = 100 --广场登录

SUB_MB_LOGON_GAMEID = 1 --ID登录
SUB_MB_LOGON_ACCOUNTS = 2 --帐号登录
SUB_MB_REGISTER_ACCOUNTS = 3 --注册帐号
SUB_MB_LOGON_OTHERPLATFORM = 4 --其他登录
SUB_MB_LOGON_VISITOR = 5 --游客登录
SUB_MB_ONLINE_CHECK = 6 --在线检测

SUB_GP_LOGON_SUCCESS = 100 --登陆成功
SUB_GP_LOGON_ERROR = 101 --登陆失败
SUB_GP_LOGON_FINISH = 102 --登陆完成
SUB_GP_LOGON_REPLACE = 103 --被登陆
SUB_GP_ASK_REGISTER_REQ = 104 --请求注册回复
SUB_GP_REGISTER_RESULT_REQ = 108 --注册结果回复

SUB_GP_LOGON_MESSAGE = 105 --消息
SUB_GP_LOGON_UPDATEINFO = 106 --更新用户信息
SUB_GP_LOGON_AddGoldPage = 107 --充值面页，最长为128位字符串，长度为实际长度
SUB_GP_LOGON_LOCKPC = 111 --固定机器
SUB_GP_LOGON_ATTRACT_CHANGE = 112 --魅力兑换
SUB_GP_LOGON_SENDLOG_LIST = 120 --赠送列表
SUB_GP_LOGON_BANK = 121 --银行功能
SUB_GP_LOGON_ONLINE_SERVER = 122 --登陆在线服务器

MDM_MB_SERVER_LIST = 101 --列表消息

SUB_MB_LIST_SERVER = 101 --房间列表
SUB_MB_LIST_MATCH = 102 --比赛列表	
SUB_MB_LIST_FINISH = 200 --发送完成
SUB_GP_LIST_CONFIG = 105 --列表配置
SUB_GP_LIST_PROCESS = 106 --进程列表
SUB_GP_LIST_PROP = 107 --道具列表
SUB_GP_LIST_APPLY = 108 --报名列表

MDM_KN_COMMAND = 0 --内核命令
SUB_KN_DETECT_SOCKET = 1 --心跳

MDM_GR_LOGON = 1 --房间登录
--登录模式
SUB_GR_LOGON_USERID = 1 --I D 登录
SUB_GR_LOGON_MOBILE = 2 --手机登录
SUB_GR_LOGON_ACCOUNTS = 3 --帐户登录

--登录结果
SUB_GR_LOGON_SUCCESS = 100 --登录成功
SUB_GR_LOGON_FAILURE = 101 --登录失败
SUB_GR_LOGON_FINISH = 102 --登录完成
SUB_GR_UPDATE_NOTIFY = 200 --升级提示

--配置命令
MDM_GR_CONFIG = 2 --配置信息

SUB_GR_CONFIG_COLUMN = 100 --列表配置
SUB_GR_CONFIG_SERVER = 101 --房间配置
SUB_GR_CONFIG_PROPERTY = 102 --道具配置
SUB_GR_CONFIG_FINISH = 103 --配置完成
SUB_GR_CONFIG_USER_RIGHT = 104 --玩家权限

--房间内操作
MDM_GR_USER = 3

SUB_GR_USER_COME = 100 --用户进入
SUB_GR_USER_SCORE = 101 --用户分数
SUB_GR_USER_SITDOWN = 3 --坐下请求
SUB_GR_USER_STATUS = 102 --用户状态
SUB_GR_SIT_FAILED = 103 --坐下失败
SUB_GR_USER_WAIT_DISTRUBUTE = 12 --等待匹配

MDM_GR_STATUS = 4 --状态信息

SUB_GR_TABLE_INFO = 100 --桌子信息
SUB_GR_TABLE_STATUS = 101 --桌子状态

--系统命令
MDM_CM_SYSTEM = 1000

SUB_CM_SYSTEM_MESSAGE = 1 --系统消息
SUB_CM_ACTION_MESSAGE = 2 --动作消息
SUB_CM_DOWN_LOAD_MODULE = 3 --下载消息

MDM_GR_APP = 300 --街机命令信息

SUB_GR_C_APP_LOGON = 1 --ID登录
SUB_GR_C_APP_STANDUP = 2 --起来
SUB_GR_C_APP_SENDMSG = 3 --发送消息

SUB_GR_S_APP_LOGON_SUCCESS = 100 --登录成功
SUB_GR_S_APP_LOGON_FAILURE = 101 --登录失败
SUB_GR_S_APP_SENDMSG = 3 --接收消息