module("pt_gate", package.seeall)

MDM_MB_LOGON = 100 --广场登录

SUB_MB_LOGON_GAMEID = 1 --ID登录
SUB_MB_LOGON_ACCOUNTS = 2 --帐号登录
SUB_MB_REGISTER_ACCOUNTS = 3 --注册帐号
SUB_MB_LOGON_OTHERPLATFORM = 4 --其他登录
SUB_MB_LOGON_VISITOR = 5 --游客登录
SUB_MB_ONLINE_CHECK = 6 --在线检测
SUB_MB_FANLI = 8 --消费返利
SUB_MB_ONE_KEY_LOGIN = 10 --一键登录

SUB_MB_LOGON_OTHERPLATFORM = 4 --其他登录
SUB_MB_WXBUILD_ACCOUNTS = 8 --微信首次登陆创建
SUB_MB_WXBIND_ACCOUNTS = 9 --微信首次登陆绑定账号

SUB_MB_WXACCOUNTD_RESUALT = 102 --微信创建/绑定 结果

SUB_GP_LOGON_SUCCESS = 100 --登陆成功
SUB_GP_LOGON_ERROR = 101 --登陆失败
SUB_GP_LOGON_FINISH = 102 --登陆完成
SUB_GP_LOGON_REPLACE = 103 --被登陆
SUB_GP_ASK_REGISTER_REQ = 104 --请求注册回复
SUB_GP_REGISTER_RESULT_REQ = 108 --注册结果回复

SUB_GP_LOGON_MESSAGE = 105 --消息
SUB_GP_LOGON_UPDATEINFO = 106 --更新用户信息
SUB_GP_LOGON_AddGoldPage = 107 --充值面页，最长为128位字符串，长度为实际长度
SUB_GP_LOGON_LOCKPC = 111 --固定机器
SUB_GP_LOGON_ATTRACT_CHANGE = 112 --魅力兑换
SUB_GP_LOGON_SENDLOG_LIST = 120 --赠送列表
SUB_GP_LOGON_BANK = 121 --银行功能
SUB_GP_LOGON_ONLINE_SERVER = 122 --登陆在线服务器

MDM_MB_SERVER_LIST = 101 --列表消息

SUB_MB_LIST_KIND = 100 --种类列表
SUB_MB_LIST_SERVER = 101 --房间列表
SUB_MB_LIST_MATCH = 102 --比赛列表	
SUB_MB_LIST_FINISH = 200 --发送完成
SUB_GP_LIST_CONFIG = 105 --列表配置
SUB_GP_LIST_PROCESS = 106 --进程列表
SUB_GP_LIST_PROP = 107 --道具列表
SUB_GP_LIST_APPLY = 108 --报名列表

MDM_KN_COMMAND = 0 --内核命令
SUB_KN_DETECT_SOCKET = 1 --心跳

MDM_GR_LOGON = 1 --房间登录
SUB_GR_UPDATE_NOTIFY = 200 --升级提示
SUB_GP_MATCH_SIGNUPINFO = 106 --比赛报名记录

MDM_GP_USER_SERVICE = 3 --用户服务

SUB_GP_MODIFY_MACHINE = 100 --修改机器
SUB_GP_MODIFY_LOGON_PASS = 101 --修改密码
SUB_GP_MODIFY_INSURE_PASS = 102 --修改保险密码
SUB_GP_MODIFY_UNDER_WRITE = 103 --修改签名

SUB_GP_SETWXFACE = 191--设置微信头像（没有返回）
SUB_GP_GETWXFACE = 192--设置微信头像
SUB_GP_GETWXFACE_RESULT	= 193--获取头像返回
SUB_GP_GETRICHLIST = 194 --获取排行榜
SUB_GP_GETRICHLIST_RESULT = 195 --获取排行榜返回

SUB_GP_GETMATCHRANDLIST = 196 --获取比赛排行榜  发空
SUB_GP_GETMATCHRANDLIST_RESULT = 197 --获取比赛排行榜返回

SUB_GP_C_USER_WX_SHAREINFO = 174 --微信分享后获取轮盘奖励信息
SUB_GP_S_USER_WX_SHAREINFO_RESULT = 175 --微信分享后获取轮盘奖励信息

SUB_GP_C_USER_WX_GETPRICE = 176 --微信轮盘开奖
SUB_GP_S_USER_WX_GETPRICE_RESULT = 177 --微信轮盘开奖结果

SUB_GP_USER_WX_INPUTSPRINFO = 178 --微信完善推广员信息
SUB_GP_USER_WX_INPUTSPRINFO_RESULT = 179 --返回结果

SUB_GP_USER_WX_GETSPRINFO = 180 --获取推广员信息
SUB_GP_USER_WX_GETSPRINFO_RESULT = 181 --获取推广员信息结果

SUB_GP_USER_WX_INPUTSPRINFO2 = 182 --微信完善推广员信息,需要推广号跟登录密码
SUB_GP_USER_WX_INPUTSPRINFO2_RESULT = 183 --返回结果

SUB_GP_USER_GETPAYCODE = 184 --获取付款码（1分钟有效）
SUB_GP_USER_GETPAYCODE_RESULT = 185 --返回结果

SUB_GP_USER_GETPAYCODE2 = 189    --获取道具扣除付款码（1分钟有效）
SUB_GP_USER_GETPAYCODE2_RESULT = 190    --返回结果

SUB_GP_USER_GETSYSNAME = 186 --获取系统名称
SUB_GP_USER_GETSYSNAME_RESULT = 187 --返回结果

SUB_GP_USER_EXCHANGE = 188 --兑换连接

SUB_GP_MATCH_SIGNUP = 200 --报名
SUB_GP_MATCH_SIGNUP_RESULT = 202 --报名结果

SUB_GP_MATCHPRICEGET = 330 --比赛奖励领取
SUB_GP_MATCHPRICEGET_RESULT = 331 --比赛奖励领取结果 

SUB_GP_OPERATE_SUCCESS = 500 --操作成功
SUB_GP_OPERATE_FAILURE = 501 --操作失败

--命令
MDM_SCORE_UPDOWN = 10 --上下分

--事件id
SUB_SCORE_GET = 1	 --获取一申请的上下分信息
SUB_SCORE_ADD = 3 --申请上下分
SUB_SCORE_DEL	 = 5	 --取消申请

SUB_SCORE_GET_RESUALT = 101 --获取一申请的上下分信息
SUB_SCORE_ADD_RESUALT = 103 --申请上下分
SUB_SCORE_DEL_RESUALT = 107 --取消申请

SUB_MB_GETFBZLINFO = 14 --获取za/fb信息
SUB_MB_GETFBZLINFORESULT = 114 --获取za/fb信息结果

SUB_GP_C_CHECKIN_QUERY = 220 --签到查询
SUB_GP_S_CHECKIN_INFO = 221 --签到信息
SUB_GP_C_CHECKIN_DONE = 222 --执行签到
SUB_GP_S_CHECKIN_RESULT = 223 --签到结果

SUB_GP_C_BASEENSURE_LOAD = 260 --查询低保
SUB_GP_C_BASEENSURE_TAKE = 261 --领取低保
SUB_GP_S_BASEENSURE_PARAMETER = 262 --低保参数
SUB_GP_S_BASEENSURE_RESULT = 263 --领取结果

SUB_GP_C_USER_ENABLE_INSURE = 160 --开通银行
SUB_GP_C_QUERY_INSURE_INFO = 165 --查询银行
SUB_GP_S_USER_INSURE_INFO = 164 --银行信息
SUB_GP_C_USER_SAVE_SCORE = 161 --存款操作
SUB_GP_C_USER_TAKE_SCORE = 162 --取款操作
SUB_GP_S_USER_INSURE_SUCCESS = 166 --存取成功
SUB_GP_S_USER_INSURE_FAILURE = 167 --存取失败
SUB_GP_S_USER_INSURE_ENABLE_RESULT = 170 --开通结果
SUB_GP_C_USER_ENABLE_INSURE_WX = 171 --微信用户开通银行

SUB_GP_C_USER_BIND_WX = 172 --用户绑定微信
SUB_GP_S_USER_BIND_WX_RESULT = 173 --用户绑定微信结果

SUB_GP_C_MB_WRITE_ORDER = 247 --写入订单
SUB_GP_S_MB_WRITE_ORDER_REASULT = 248 --订单结果

SUB_GP_CS_PROPERTY_INFO = 225 --道具信息
SUB_GP_S_PROPERTY_USER_INFO = 227 --用户道具
SUB_GP_C_SEND_PROPERTY = 229 --赠送道具
SUB_GP_S_SEND_PROPERTY_REASULT = 229 --赠送道具结果
SUB_GP_C_BUY_PROPERTY = 226 --购买道具
SUB_GP_S_BUY_PROPERTY_REASULT = 226 --购买道具结果
SUB_GP_C_SELL_PROPERTY = 228 --回收道具
SUB_GP_S_SELL_PROPERTY_REASULT = 228 --回收道具结果
SUB_GP_SEND_PROPERTY = 230 --赠送道具
SUB_GP_SEND_PROPERTY_REASULT = 230 --赠送道具

SUB_GP_C_MODIFY_MACHINE = 100 --修改机器

MDM_APP = 120 --四网通主命令

SUB_APP_USER_STATUS = 103 --玩家当前信息，跟着登陆成功一起发过来

SUB_APP_SITDOWN = 5 --手机端 发送 合集坐下
SUB_APP_SITDOWN_WX = 7 --手机端 微信登录
SUB_APP_STANDUP = 6 --手机端 发送 合集起来
SUB_APP_GET_SERVER = 8 --获取房间

SUB_APP_SITDOWN_RESUALT = 105 --街机坐下结果
SUB_APP_GET_SERVER_SUCCESS = 108 --获取房间信息成功
SUB_APP_GET_SERVER_FAILURE = 109 --获取房间找不到房间

--刷币器主命令
MDM_COIN_DEVICE = 300 --刷币器主命令

--手机端信息
SUB_COIN_MBLOGON = 1 --手机连接服务器--返回金币数据。。
SUB_COIN_MBINFO = 3	--手机获取当前投币信息
SUN_COIN_MBUPSCORE = 5 --手机上分
SUN_COIN_MBDOWNSCORE = 7 --手机下分（下分为全下，并且断开鱼刷币器的连接）

SUB_COIN_MBLOGON_RESULT = 101 --手机连接服务器结果
SUB_COIN_MBINFO_RESULT = 103 --当前投币信息返回
SUN_COIN_MBUPSCORE_RESULT = 105 --手机上分结果
SUN_COIN_MBDOWNSCORE_RESUL = 107 --手机下分结果（下分为全下，并且断开鱼刷币器的连接）

SUB_GP_CHATINFO = 204   --获取聊天信息
SUB_GP_CHATINFO_RESULT = 205   --返回是否有新的聊天信息
SUB_GP_GETCHATINFO = 206   --获取所有未读信息
SUB_GP_GETCHATINFO_RESULT = 207   --返回所有获取未读信息
SUB_GP_GETCHATINFO_END = 208   --获取所有未读信息已结束
SUB_GP_CHATSEND = 209   --发送聊天

MDM_PAIMAIHANG = 800 --拍卖行事件

SUB_PMH_UPPROP = 1 --上架商品
SUB_PMH_BUYPROP = 3 --购买上架物品
SUB_PMH_USERINFO = 5 --获取用户信息
SUB_PMH_USERINFO_MODIFY = 7 --更新用户信息

SUB_PMH_UPPROP_RESULT = 2 --上架商品
SUB_PMH_BUYPROP_RESULT = 4 --购买上架物品
SUB_PMH_USERINFO_RESULT = 6 --获取用户信息
SUB_PMH_USERINFO_MODIFY_RESULT = 8 --更新用户信息

MDM_SET_JIGUANG = 100 --发送极光推送所需参数 主命令
SUB_MB_SET_JIGUANG = 11 --发送极光推送所需参数 子命令

SUB_PMH_USERINFONEW = 14 --获取用户信息
SUB_PMH_USERINFONEW_MODIFY = 15 --更新用户信息
SUB_PMH_USERINFONEW_RESULT = 16 --获取用户信息
SUB_PMH_USERINFONEW_MODIFY_RESULT = 17 --更新用户信息