--常量定义
-- 游戏类型
GAMBLETYPE_INVALID = -1
GAMBLETYPE_ANIMALGAME = 0	--3d动物
GAMBLETYPE_ENJOYGAME = 1		--小游戏，庄闲和
GAMBLETYPE_MAX = 2

--动物类型定义
ANIMALTYPE_INVALID	= -1
ANIMALTYPE_LION	= 0
ANIMALTYPE_PANDA = 1  
ANIMALTYPE_MONKEY = 2  
ANIMALTYPE_RABBIT = 3  
ANIMALTYPE_MAX = 4  -- 最大值

--颜色类型定义
COLORTYPE_INVALID = -1
COLORTYPE_RED = 0
COLORTYPE_GREEN = 1
COLORTYPE_YELLOW = 2
COLORTYPE_MAX = 3

--动物模式的开奖模式
ANIMALPRIZEMODE_INVALID = -1
ANIMALPRIZEMODE_SINGLEANIMALSINGLECOLOR = 0
ANIMALPRIZEMODE_ALLANIMALSINGLECOLR = 1
ANIMALPRIZEMODE_ALLCOLORSINGLEANIMAL = 2
ANIMALPRIZEMODE_SYSPRIZE = 3
ANIMALPRIZEMODE_REPEATTIME = 4
ANIMALPRIZEMODE_FLASH = 5
ANIMALPRIZEMODE_MAX = 6

--庄闲和游戏定义
ENJOYGAMETYPE_INVALID = -1
ENJOYGAMETYPE_ZHUANG = 0
ENJOYGAMETYPE_XIAN = 1
ENJOYGAMETYPE_HE = 2
ENJOYGAMETYPE_MAX = 3 --最大值

-- 事件响应
GAME_LSWC_GAME_FREE = "GAME_LSWC_GAME_FREE"
GAME_LSWC_GAME_START = "GAME_LSWC_GAME_START"
GAME_LSWC_PLACE_JETTON = "GAME_LSWC_PLACE_JETTON"
GAME_LSWC_GAME_END = "GAME_LSWC_GAME_END"
GAME_LSWC_GAME_SHOWRESULT = "GAME_LSWC_GAME_SHOWRESULT"
-- GAME_LSWC_CHANGE_USER_SCORE = "GAME_LSWC_CHANGE_USER_SCORE"
GAME_LSWC_SEND_RECORD = "GAME_LSWC_SEND_RECORD"
GAME_LSWC_PLACE_JETTON_FAIL = "GAME_LSWC_PLACE_JETTON_FAIL"
GAME_LSWC_CLEAR_JETTON = "GAME_LSWC_CLEAR_JETTON"
GAME_LSWC_CLOSE_BET_VIEW = "GAME_LSWC_CLOSE_BET_VIEW"
GAME_LSWC_GS_PLACE_JETTON = "GAME_LSWC_GS_PLACE_JETTON"
GAME_LSWC_GS_GAME_SCENE = "GAME_LSWC_GS_GAME_SCENE"

MUSIC_BACK = "liushiwangchao/res/sound/showTimes.mp3"
MUSIC_START = "liushiwangchao/res/sound/start.wav"
MUSIC_END = "liushiwangchao/res/sound/end.wav"
MUSIC_FREE = "liushiwangchao/res/sound/free.wav"
MUSIC_BET = "liushiwangchao/res/sound/bet.wav"
MUSIC_STOP_BET = "liushiwangchao/res/sound/buyFromHand.wav"