local DSxfish = class("DSxfish", function()
    return cc.Node:create()
end)

function DSxfish:ctor(num1,num2)
    self.sp1 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
    self.sp1:setPosition(-60,0)
    self.sp2 = Fish.new(num1)
    self.sp2:setPosition(-60,0)
    self:addChild(self.sp1)
    self:addChild(self.sp2)
    self.sp2:setRotation(-90)
    self.sp3 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
    self.sp3:setPosition(60,0)
    self.sp4 = Fish.new(num1)
    self.sp4:setPosition(60,0)
    self:addChild(self.sp3)
    self:addChild(self.sp4)
    self.sp4:setRotation(-90)
    self.sp5 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
    self.sp5:setPosition(-180,0)
    self.sp6 = Fish.new(num1)
    self.sp6:setPosition(-180,0)
    self:addChild(self.sp5)
    self:addChild(self.sp6)
    self.sp6:setRotation(-90)
    self.sp7 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
    self.sp7:setPosition(180,0)
    self.sp8 = Fish.new(num1)
    self.sp8:setPosition(180,0)
    self:addChild(self.sp7)
    self:addChild(self.sp8)
    self.sp8:setRotation(-90)
	self:play()
end
function DSxfish:play()
    local rotate = cc.RotateBy:create(6,-360)
    self.sp1:runAction(cc.RepeatForever:create(rotate))
    local rotate1 = cc.RotateBy:create(6,-360)
    self.sp3:runAction(cc.RepeatForever:create(rotate1))
    local rotate2 = cc.RotateBy:create(6,-360)
    self.sp5:runAction(cc.RepeatForever:create(rotate2))
	local rotate3 = cc.RotateBy:create(6,-360)
    self.sp7:runAction(cc.RepeatForever:create(rotate3))
end
function DSxfish:stop1()
    self.sp1:stopAllActions()
    self.sp3:stopAllActions()
    self.sp5:stopAllActions()
    self.sp7:stopAllActions()
    --self.sp2:playac()
    --self.sp4:playac()
    --self.sp6:playac()
    --self.sp8:playac()
end
return DSxfish