local Dsyuan = class("Dsyuan", function()
    return cc.Node:create()
end)
function Dsyuan:ctor(num1)
	self.sp1 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
	self.sp2 = Fish.new(num1)
	self:addChild(self.sp1)
	self:addChild(self.sp2)
	self.sp2:setRotation(-90)
	self.sp3 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
	self.sp3:setPosition(-120,0)
	self.sp4 = Fish.new(num1)
	self.sp4:setPosition(-120,0)
	self:addChild(self.sp3)
	self:addChild(self.sp4)
	self.sp4:setRotation(-90)
	self.sp5 = cc.Sprite:createWithSpriteFrameName("XY_dish.png")
	self.sp5:setPosition(120,0)
	self.sp6 = Fish.new(num1)
	self.sp6:setPosition(120,0)
	self:addChild(self.sp5)
	self:addChild(self.sp6)
	self.sp6:setRotation(-90)
	self:play()
end
function Dsyuan:play()
	local rotate = cc.RotateBy:create(6,-360)
    self.sp1:runAction(cc.RepeatForever:create(rotate))
    local rotate1 = cc.RotateBy:create(6,-360)
    self.sp3:runAction(cc.RepeatForever:create(rotate1))
    local rotate2 = cc.RotateBy:create(6,-360)
    self.sp5:runAction(cc.RepeatForever:create(rotate2))
end
function Dsyuan:stop1()
    self.sp1:stopAllActions()
    self.sp3:stopAllActions()
    self.sp5:stopAllActions()
    --self.sp2:playac()
    --self.sp4:playac()
    --self.sp6:playac()
end

return Dsyuan