local DSxfish = class("DSxfish", function()
    return cc.Node:create()
end)
local m_BackWidth = 120
function DSxfish:ctor()
    self.sp1 = cc.Sprite:createWithSpriteFrameName("YQS_dishBack1.png")
    self.sp2 = Fish.new(22)
    self:addChild(self.sp1,-1)
    self:addChild(self.sp2,0)
    self.sp2:setRotation(0)

    self.sp3 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
    self.sp3:setPosition(-m_BackWidth*0.75, m_BackWidth*0.75)
    self.sp4 = Fish.new(11)
    self.sp4:setPosition(-m_BackWidth*0.75, m_BackWidth*0.75)
    self:addChild(self.sp3,-1)
    self:addChild(self.sp4,1)
    self.sp4:setRotation(-90)

    self.sp5 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
    self.sp5:setPosition(m_BackWidth*0.75, m_BackWidth*0.75)
    self.sp6 = Fish.new(11)
    self.sp6:setPosition(m_BackWidth*0.75, m_BackWidth*0.75)
    self:addChild(self.sp5,-1)
    self:addChild(self.sp6,1)
    self.sp6:setRotation(-90)

    self.sp9 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
    self.sp9:setPosition(m_BackWidth*0.75, -m_BackWidth*0.75)
    self.sp10 = Fish.new(11)
    self.sp10:setPosition(m_BackWidth*0.75, -m_BackWidth*0.75)
    self:addChild(self.sp9,-1)
    self:addChild(self.sp10,1)
    self.sp10:setRotation(-90)

    self.sp7 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
    self.sp7:setPosition(-m_BackWidth*0.75, -m_BackWidth*0.75)
    self.sp8 = Fish.new(11)
    self.sp8:setPosition(-m_BackWidth*0.75, -m_BackWidth*0.75)
    self:addChild(self.sp7,-1)
    self:addChild(self.sp8,1)
    self.sp8:setRotation(-90)

    self:play()
end
function DSxfish:play()
    local rotate = cc.RotateBy:create(3,-360)
    self.sp1:runAction(cc.RepeatForever:create(rotate))
    local rotate1 = cc.RotateBy:create(3,-360)
    self.sp3:runAction(cc.RepeatForever:create(rotate1))
    local rotate2 = cc.RotateBy:create(3,-360)
    self.sp5:runAction(cc.RepeatForever:create(rotate2))
    local rotate3 = cc.RotateBy:create(3,-360)
    self.sp7:runAction(cc.RepeatForever:create(rotate3))
    local rotate3 = cc.RotateBy:create(3,-360)
    self.sp9:runAction(cc.RepeatForever:create(rotate3))
end
function DSxfish:stop1()
    self.sp1:stopAllActions()
    self.sp3:stopAllActions()
    self.sp5:stopAllActions()
    self.sp7:stopAllActions()
    --self.sp2:playac()
    --self.sp4:playac()
    --self.sp6:playac()
    --sself.sp8:playac()
end
return DSxfish