local Dsyuan = class("Dsyuan", function()
    return cc.Node:create()
end)
local m_BackWidth = 120
function Dsyuan:ctor(num1)
	if num1 == 1 then
		self.sp1 = cc.Sprite:createWithSpriteFrameName("YQS_dishBack1.png")
		self.sp2 = Fish.new(18)
		self:addChild(self.sp1,-1)
		self:addChild(self.sp2,0)
		self.sp2:setRotation(0)

		self.sp3 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
		self.sp3:setPosition(-m_BackWidth*0.75,m_BackWidth*0.75)
		self.sp4 = Fish.new(12)
		self.sp4:setPosition(-m_BackWidth*0.75,m_BackWidth*0.75)
		self:addChild(self.sp3,-1)
		self:addChild(self.sp4,1)
		self.sp4:setRotation(-90)

		self.sp5 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
		self.sp5:setPosition(m_BackWidth*0.75, m_BackWidth*0.75)
		self.sp6 = Fish.new(12)
		self.sp6:setPosition(m_BackWidth*0.75, m_BackWidth*0.75)
		self:addChild(self.sp5,-1)
		self:addChild(self.sp6,1)
		self.sp6:setRotation(-90)

		self.sp7 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
		self.sp7:setPositionY(-m_BackWidth)
		self.sp8 = Fish.new(12)
		self.sp8:setPositionY(-m_BackWidth)
		self:addChild(self.sp7,-1)
		self:addChild(self.sp8,1)
		self.sp8:setRotation(-90)

	elseif num1 == 2 then

		self.sp1 = cc.Sprite:createWithSpriteFrameName("YQS_dishBack1.png")
		self.sp2 = Fish.new(16)
		self:addChild(self.sp1,-1)
		self:addChild(self.sp2,0)
		self.sp2:setRotation(-90)

		self.sp3 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
		self.sp3:setPosition(-m_BackWidth*0.75,m_BackWidth*0.75)
		self.sp4 = Fish.new(13)
		self.sp4:setPosition(-m_BackWidth*0.75,m_BackWidth*0.75)
		self:addChild(self.sp3,-1)
		self:addChild(self.sp4,1)
		self.sp4:setRotation(-90)

		self.sp5 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
		self.sp5:setPosition(m_BackWidth*0.75, m_BackWidth*0.75)
		self.sp6 = Fish.new(13)
		self.sp6:setPosition(m_BackWidth*0.75, m_BackWidth*0.75)
		self:addChild(self.sp5,-1)
		self:addChild(self.sp6,1)
		self.sp6:setRotation(-90)

		self.sp7 = cc.Sprite:createWithSpriteFrameName("YQS_dish.png")
		self.sp7:setPositionY(-m_BackWidth)
		self.sp8 = Fish.new(13)
		self.sp8:setPositionY(-m_BackWidth)
		self:addChild(self.sp7,-1)
		self:addChild(self.sp8,1)
		self.sp8:setRotation(-90)
	end
	self:play()
end
function Dsyuan:play()
	local rotate = cc.RotateBy:create(3,-360)
    self.sp1:runAction(cc.RepeatForever:create(rotate))
    local rotate1 = cc.RotateBy:create(3,-360)
    self.sp3:runAction(cc.RepeatForever:create(rotate1))
    local rotate2 = cc.RotateBy:create(3,-360)
    self.sp5:runAction(cc.RepeatForever:create(rotate2))
    local rotate2 = cc.RotateBy:create(3,-360)
    self.sp7:runAction(cc.RepeatForever:create(rotate2))
end
function Dsyuan:stop1()
    self.sp1:stopAllActions()
    self.sp3:stopAllActions()
    self.sp5:stopAllActions()
    --self.sp2:playac()
    --self.sp4:playac()
    --self.sp6:playac()
end
return Dsyuan