--常量定义
GAME_EXCHANGE_SCORE_SUCCESS = "GAME_EXCHANGE_SCORE_SUCCESS" --兑换游戏币成功
GAME_EXCHANGE_GOLD_SUCCESS = "GAME_EXCHANGE_GOLD_SUCCESS" --兑换金币成功
GAME_EVENT_STATUS_IDLE = "GAME_EVENT_STATUS_IDLE" --游戏空闲
GAME_EVENT_STATUS_START = "GAME_EVENT_STATUS_START" --游戏开始
GAME_EVENT_STATUS_END = "GAME_EVENT_STATUS_END" --游戏开奖

GAME_MESSAGE_GAME_SCENE_RESULT = "GAME_MESSAGE_GAME_SCENE_RESULT" --进入游戏机游戏开始
GAME_MESSAGE_GAME_PLACE_JETTON_RESULT = "GAME_MESSAGE_GAME_PLACE_JETTON_RESULT" --下注后第一次点开始 TODO
GAME_MESSAGE_DEAL_CARD_RESULT = "GAME_MESSAGE_DEAL_CARD_RESULT" --发牌
GAME_MESSAGE_SWITCH_CARD_RESULT = "GAME_MESSAGE_SWITCH_CARD_RESULT" --换牌
GAME_MESSAGE_COMPARE_CARD_RESULT = "GAME_MESSAGE_COMPARE_CARD_RESULT" --比倍


GAME_MESSAGE_GAME_END_RESULT = "GAME_MESSAGE_GAME_END_RESULT" --游戏结束
GAME_MESSAGE_GAME_FRAME_RESULT = "GAME_MESSAGE_GAME_FRAME_RESULT" --发给框架
