--常量定义
GAME_EXCHANGE_SCORE_SUCCESS = "GAME_EXCHANGE_SCORE_SUCCESS" --兑换游戏币成功
GAME_EXCHANGE_GOLD_SUCCESS = "GAME_EXCHANGE_GOLD_SUCCESS" --兑换金币成功

GAME_MESSAGE_GAMEFREE = "GAME_MESSAGE_GAMEFREE" --游戏空闲
GAME_MESSAGE_GAMEPLAY = "GAME_MESSAGE_GAMEPLAY" --正在游戏
GAME_MESSAGE_GAMESTART = "GAME_MESSAGE_GAMESTART" --开始游戏
GAME_MESSAGE_GETSCORE = "GAME_MESSAGE_GETSCORE" --下注结果
GAME_MESSAGE_BIBEIDATAM = "GAME_MESSAGE_BIBEIDATAM" --下注失败
GAME_MESSAGE_BIBEISTART = "GAME_MESSAGE_BIBEISTART" --比倍结果 游戏结束
GAME_MESSAGE_GAMERECORD ="GAME_MESSAGE_GAMERECORD" --游戏路单

GAME_MESSAGE_GAMEJETTONLIST="GAME_MESSAGE_GAMEJETTONLIST" 