
FISH_KIND_COUNT = 40
BULLET_KIND_COUNT = 12
kRESOLUTIONWIDTH = 1366
kRESOLUTIONHEIGHT = 768

GAME_MESSAGE_BUYU_GAME_CONFIG = "GAME_MESSAGE_BUYU_GAME_CONFIG"
GAME_MESSAGE_BUYU_FISH_TRACE = "GAME_MESSAGE_BUYU_FISH_TRACE"
GAME_MESSAGE_BUYU_EXCHANGE_FISHSCORE = "GAME_MESSAGE_BUYU_EXCHANGE_FISHSCORE"
GAME_MESSAGE_BUYU_USER_FIRE = "GAME_MESSAGE_BUYU_USER_FIRE"
GAME_MESSAGE_BUYU_CATCH_FISH = "GAME_MESSAGE_BUYU_CATCH_FISH"
GAME_MESSAGE_BUYU_BULLET_ION_TIMEOUT = "GAME_MESSAGE_BUYU_BULLET_ION_TIMEOUT"
GAME_MESSAGE_BUYU_HIT_FISH_LK = "GAME_MESSAGE_BUYU_HIT_FISH_LK"
GAME_MESSAGE_BUYU_SWITCH_SCENE = "GAME_MESSAGE_BUYU_SWITCH_SCENE"
GAME_MESSAGE_LOCK_TIMEOUT = "GAME_MESSAGE_LOCK_TIMEOUT"
GAME_MESSAGE_BUYU_GF_SCENE = "GAME_MESSAGE_BUYU_GF_SCENE"
GAME_MESSAGE_SHAKE_SCREEN = "GAME_MESSAGE_SHAKE_SCREEN"
GAME_MESSAGE_MATCH_TOP = "GAME_MESSAGE_MATCH_TOP"
GAME_MESSAGE_GF_MESSAGE = "GAME_MESSAGE_GF_MESSAGE"

GAME_MESSAGE_RED_ENVELOPE_FLAG = "GAME_MESSAGE_RED_ENVELOPE_FLAG"
GAME_MESSAGE_RED_ENVELOPE_SEND = "GAME_MESSAGE_RED_ENVELOPE_SEND"

GAME_MESSAGE_USER_FIRE_SPEED = "GAME_MESSAGE_USER_FIRE_SPEED"

GAME_MESSAGE_BUYU_FISH_LINE = "GAME_MESSAGE_BUYU_FISH_LINE"