--常量定义
GAME_EXCHANGE_SCORE_SUCCESS = "GAME_EXCHANGE_SCORE_SUCCESS" --兑换游戏币成功
GAME_EXCHANGE_GOLD_SUCCESS = "GAME_EXCHANGE_GOLD_SUCCESS" --兑换金币成功
GAME_EVENT_STATUS_IDLE = "GAME_EVENT_STATUS_IDLE" --游戏空闲
GAME_EVENT_STATUS_START = "GAME_EVENT_STATUS_START" --游戏开始
GAME_EVENT_STATUS_END = "GAME_EVENT_STATUS_END" --游戏开奖

GAME_MESSAGE_GAMEPLACEJETTONRESULT = "GAME_MESSAGE_GAMEPLACEJETTONRESULT" --押注返回
GAME_MESSAGE_CLEARJETTONRESULT = "GAME_MESSAGE_CLEARJETTONRESULT"
GAME_MESSAGE_CONTINUEJETTONRESULT = "GAME_MESSAGE_CONTINUEJETTONRESULT"