
FISH_KIND_COUNT = 60
BULLET_KIND_COUNT = 12
kRESOLUTIONWIDTH = 1366
kRESOLUTIONHEIGHT = 768
--kResolutionWidth = 1366;
--kResolutionHeight = 768;
SCENE_KIND_1_TRACNENUM=210;
SCENE_KIND_2_TRACNENUM=200 + 7 * 2;
SCENE_KIND_3_TRACNENUM=(50 + 40 + 30 + 1) * 2;
SCENE_KIND_4_TRACNENUM=8 * 8;
SCENE_KIND_5_TRACNENUM=(40 + 40 + 24 + 13 + 1) * 2;

GAME_PLAYER=8
GAME_PLAYERCLIENT= 8;
GAME_MESSAGE_BUYU_GAME_CONFIG = "GAME_MESSAGE_BUYU_GAME_CONFIG"
GAME_MESSAGE_BUYU_FISH_TRACE = "GAME_MESSAGE_BUYU_FISH_TRACE"
GAME_MESSAGE_BUYU_EXCHANGE_FISHSCORE = "GAME_MESSAGE_BUYU_EXCHANGE_FISHSCORE"
GAME_MESSAGE_BUYU_USER_FIRE = "GAME_MESSAGE_BUYU_USER_FIRE"
GAME_MESSAGE_BUYU_CATCH_FISH = "GAME_MESSAGE_BUYU_CATCH_FISH"
GAME_MESSAGE_BUYU_FISH_QUEUE="GAME_MESSAGE_BUYU_FISH_QUEUE"

GAME_MESSAGE_SUB_S_JIEJI_PLAYER_SEND="GAME_MESSAGE_SUB_S_JIEJI_PLAYER_SEND"
GAME_MESSAGE_SUB_S_BROACHCATCH_SEND="GAME_MESSAGE_SUB_S_BROACHCATCH_SEND"
--Ãÿ ‚»ŒŒÒ 
GAME_MESSAGE_SUB_S_BROACHCATCH_SEND="GAME_MESSAGE_SUB_S_BROACHCATCH_SEND"
GAME_MESSAGE_SUB_S_DIANCICATCH_SEND="GAME_MESSAGE_SUB_S_DIANCICATCH_SEND"
GAME_MESSAGE_SUB_S_MISSILECATCH_SEND="GAME_MESSAGE_SUB_S_MISSILECATCH_SEND"
GAME_MESSAGE_SUB_S_MRYCATCH_SEND="GAME_MESSAGE_SUB_S_MRYCATCH_SEND"
GAME_MESSAGE_SUB_S_BAOXANGCATCH_SEND="GAME_MESSAGE_SUB_S_BAOXANGCATCH_SEND"
GAME_MESSAGE_SUB_S_BAOXANGCATCHEND_SEND="GAME_MESSAGE_SUB_S_BAOXANGCATCHEND_SEND"
GAME_MESSAGE_SUB_S_MRY_CARCH_END_SEND="GAME_MESSAGE_SUB_S_MRY_CARCH_END_SEND"
GAME_MESSAGE_SUB_S_FREE_BULLET_END_SEND="GAME_MESSAGE_SUB_S_FREE_BULLET_END_SEND"
---------------------

GAME_MESSAGE_BUYU_BULLET_ION_TIMEOUT = "GAME_MESSAGE_BUYU_BULLET_ION_TIMEOUT"
GAME_MESSAGE_BUYU_HIT_FISH_LK = "GAME_MESSAGE_BUYU_HIT_FISH_LK"
GAME_MESSAGE_BUYU_SWITCH_SCENE = "GAME_MESSAGE_BUYU_SWITCH_SCENE"
GAME_MESSAGE_BUYU_SCENE_END="GAME_MESSAGE_BUYU_SCENE_END"
GAME_MESSAGE_LOCK_TIMEOUT = "GAME_MESSAGE_LOCK_TIMEOUT"
GAME_MESSAGE_BUYU_GF_SCENE = "GAME_MESSAGE_BUYU_GF_SCENE"
GAME_MESSAGE_SHAKE_SCREEN = "GAME_MESSAGE_SHAKE_SCREEN"
GAME_MESSAGE_MATCH_TOP = "GAME_MESSAGE_MATCH_TOP"
GAME_MESSAGE_GF_MESSAGE = "GAME_MESSAGE_GF_MESSAGE"

GAME_MESSAGE_RED_ENVELOPE_FLAG = "GAME_MESSAGE_RED_ENVELOPE_FLAG"
GAME_MESSAGE_RED_ENVELOPE_SEND = "GAME_MESSAGE_RED_ENVELOPE_SEND"

