games_config = {
[0]={
id=0,
targetId=160,
extType=1,
name="比赛房间",
path="bisaifangjian",
style=2,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=999,
},
-- [104]={
-- id=104,
-- name="百人牛牛",
-- path="bairenniuniu",
-- style=0,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=10,
-- },
-- -- [123]={
-- -- id=123,
-- -- name="飞禽走兽",
-- -- path="feiqinzoushou",
-- -- style=0,
-- -- open=1,
-- -- version=util:makeVersion(6, 7, 0, 1),
-- -- sort=8,
-- -- },
-- [164]={
-- id=164,
-- name="海盗船",
-- path="buyu3",
-- style=1,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=3,
-- },
-- [170]={
-- id=170,
-- name="抢红包",
-- path="buyu4",
-- style=1,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=4,
-- },
[219]={
id=219,
name="连环夺宝",
path="lianhuanduobao",
style=0,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=11,
resolution = {
    width = 1024,
    height = 768,
    uisuffix = "",
    autoscale = "EXACT_FIT",
},
},
-- [222]={
-- id=222,
-- name="水果世界",
-- path="shuiguoshijie",
-- style=0,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=9,
-- },
[160]={
id=160,
name="西游降魔",
path="buyu1",
style=1,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=1,
resolution = {
    width = 1280,
    height = 720,
    uisuffix = "",
    autoscale = "SHOW_ALL",
},
},
[162]={
id=162,
name="摇钱树",
path="buyu2",
style=1,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=2,
resolution = {
    width = 1280,
    height = 720,
    uisuffix = "",
    autoscale = "SHOW_ALL",
},
},
[166]={
id=166,
name="人鱼传说",
path="haiwang",
style=1,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=3,
resolution = {
    width = 1280,
    height = 720,
    uisuffix = "",
    autoscale = "SHOW_ALL",
},
},
-- -- [2010]={
-- -- id=2010,
-- -- name="天天打飞机",
-- -- path="tiantiandafeiji",
-- -- style=0,
-- -- open=0,
-- -- version=util:makeVersion(6, 7, 0, 1),
-- -- sort=11,
-- -- },
[614]={
id=614,
name="六朝狮王",
path="liushiwangchao",
style=0,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=9,
resolution = {
    width = 1280,
    height = 720,
    uisuffix = "",
    autoscale = "SHOW_ALL",
},
},
-- [203]={
-- id=203,
-- name="水浒传",
-- path="shuihuzhuan",
-- style=0,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=12,
-- },
[168]={
id=168,
name="疯狂动物城",
path="qj_animal",
tableSpecial = "ui_table168_h_t",
style=1,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=6,
resolution = {
    width = 1280,
    height = 720,
    uisuffix = "",
    autoscale = "SHOW_ALL",
},
},
-- [500]={
-- id=500,
-- name="欢乐闯关",
-- path="huanlechuangguan",
-- style=0,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=12,
-- },
-- -- [502]={
-- -- id=502,
-- -- name="戳青蛙",
-- -- path="qingwa",
-- -- style=0,
-- -- open=1,
-- -- version=util:makeVersion(6, 7, 0, 1),
-- -- sort=12,
-- -- },
-- -- [200]={
-- -- id=200,
-- -- name="斗地主",
-- -- path="doudizhu",
-- -- style=1,
-- -- open=1,
-- -- version=util:makeVersion(6, 7, 0, 1),
-- -- sort=12,
-- -- },
-- -- [220]={
-- -- id=220,
-- -- name="单挑",
-- -- path="shuangmingpai",
-- -- style=0,
-- -- open=1,
-- -- version=util:makeVersion(6, 7, 0, 1),
-- -- sort=13,
-- -- },
-- -- [181]={
-- -- id=181,
-- -- name="单挑",
-- -- path="shuangmingpai",
-- -- style=0,
-- -- open=1,
-- -- version=util:makeVersion(6, 7, 0, 1),
-- -- sort=13,
-- -- },
-- [133]={
-- id=133,
-- name="ATT2连环炮",
-- path="att2",
-- style=0,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=7,
-- },
[508]={
id=508,
name="挖财宝",
path="wacaibao",
style=0,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=22,
},
-- [223]={
-- id=223,
-- name="猜大小",
-- path="caidaxiao",
-- style=0,
-- open=1,
-- version=util:makeVersion(6, 7, 0, 1),
-- sort=23,
-- },
[224]={
id=224,
name="街霸乱斗",
path="daxiao",
style=0,
open=1,
version=util:makeVersion(6, 7, 0, 1),
sort=24,
resolution = {
    width = 1280,
    height = 720,
    uisuffix = "",
    autoscale = "SHOW_ALL",
},
},
}