--常量定义
HUNDREDBEEF_GAMESTATE_FREE = 0 --空闲状态
HUNDREDBEEF_GAMESTATE_BET = 100 --下注状态
HUNDREDBEEF_GAMESTATE_LICENSING = 101 --发牌状态
HUNDREDBEEF_GAMESTATE_WAIT      = 102

GAME_EXCHANGE_SCORE_SUCCESS = "GAME_EXCHANGE_SCORE_SUCCESS" --兑换游戏币成功
GAME_EXCHANGE_GOLD_SUCCESS = "GAME_EXCHANGE_GOLD_SUCCESS" --兑换金币成功
GAME_EVENT_STATUS_IDLE = "GAME_EVENT_STATUS_IDLE" --游戏空闲
GAME_EVENT_STATUS_START = "GAME_EVENT_STATUS_START" --游戏开始
GAME_EVENT_STATUS_END = "GAME_EVENT_STATUS_END" --游戏开奖


GAME_EVENT_GAMESCENE_PLAY = "GAME_EVENT_GAMESCENE_PLAY"   --游戏第一次进入场景
GAME_EVENT_GAMESCENE_FREE = "GAME_EVENT_GAMESCENE_FREE"
GAME_MESSAGE_GAMEAPPLYBANKER  = "GAME_MESSAGE_GAMEAPPLYBANKER" --申请上庄
GAME_MESSAGE_GAMEQUITBANKER   = "GAME_MESSAGE_GAMEQUITBANKER"  --申请下庄
GAME_MESSAGE_GAMEChANGEBANKER = "GAME_MESSAGE_GAMEChANGEBANKER"--切换庄家

GAME_MESSAGE_UPDATEUSERNAMELIST = "GAME_MESSAGE_UPDATEUSERNAMELIST" --玩家列表更新
GAME_MESSAGE_GAMEUSERENTER      = "GAME_MESSAGE_GAMEUSERENTER"      --玩家进入
GAME_MESSAGE_GAMEUSERQUIT       = "GAME_MESSAGE_GAMEUSERQUIT"       --玩家退出

GAME_MESSAGE_GAMEPLACEJETTONRESULT = "GAME_MESSAGE_GAMEPLACEJETTONRESULT" --押注返回
GAME_MESSAGE_CLEARJETTONRESULT = "GAME_MESSAGE_CLEARJETTONRESULT"
GAME_MESSAGE_CONTINUEJETTONRESULT = "GAME_MESSAGE_CONTINUEJETTONRESULT"